---
config:
  flowchart:
    curve: linear
---
graph TD;
    __start__("<p>__start__</p>")
    generate_conversational_response_node("generate_conversational_response_node")
    get_table_info_node("get_table_info_node")
    human_review_node("human_review_node<hr/><small><em>__interrupt = after</em></small>")
    generate_sql_query_node("generate_sql_query_node")
    execute_sql_query_node("execute_sql_query_node")
    __end__("<p>__end__</p>")

    __start__ --> get_table_info_node
    get_table_info_node -. "intents.RAG_QUERY" .-> __end__
    get_table_info_node -. "intents.GENERAL" .-> generate_conversational_response_node
    get_table_info_node -. "intents.SQL_QUERY" .-> generate_sql_query_node
    generate_sql_query_node --> execute_sql_query_node
    execute_sql_query_node --> generate_conversational_response_node
    generate_conversational_response_node --> __end__

    classDef default fill:#f2f0ff,line-height:1.2
    classDef first fill-opacity:0
    classDef last fill:#bfb6fc